#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${ROOT_DIR}/deploy.conf"
ENV_DIR="${ROOT_DIR}/container_env_files"
CREDENTIALS_FILE="${ROOT_DIR}/.credentials"

generate_secret() {
    openssl rand -base64 32 | tr -d '/+=' | cut -c1-32
}

generate_password() {
    openssl rand -base64 16 | tr -d '/+=' | cut -c1-16
}

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Error: Configuration file not found: $CONFIG_FILE"
    echo "Run: cp deploy.conf.example deploy.conf"
    exit 1
fi

source "$CONFIG_FILE"

DJANGO_SECRET_KEY=$(generate_secret)
CGW_AUTH_TOKEN=$(generate_secret)
ADMIN_PASSWORD=$(generate_password)
POSTGRES_PASSWORD=$(generate_password)

mkdir -p "$ENV_DIR"

cat > "${ENV_DIR}/txs.env" <<EOF
PYTHONPATH=/app/
DJANGO_SETTINGS_MODULE=config.settings.production
DJANGO_SECRET_KEY='${DJANGO_SECRET_KEY}'
DEBUG=0
DATABASE_URL=psql://postgres:${POSTGRES_PASSWORD}@txs-db:5432/postgres
ETH_L2_NETWORK=1
REDIS_URL=redis://txs-redis:6379/0
CELERY_BROKER_URL=amqp://guest:guest@txs-rabbitmq/
DJANGO_ALLOWED_HOSTS="*"
FORCE_SCRIPT_NAME=/txs/
CSRF_TRUSTED_ORIGINS="http://${DOMAIN:-localhost}:${PORT:-8000}"
EVENTS_QUEUE_URL=amqp://general-rabbitmq:5672
EVENTS_QUEUE_ASYNC_CONNECTION=True
EVENTS_QUEUE_EXCHANGE_NAME="safe-transaction-service-events"
DJANGO_SUPERUSER_USERNAME=root
DJANGO_SUPERUSER_PASSWORD=${ADMIN_PASSWORD}
DJANGO_SUPERUSER_EMAIL=admin@safe.local
EOF

cat > "${ENV_DIR}/cfg.env" <<EOF
PYTHONDONTWRITEBYTECODE=true
SECRET_KEY=${DJANGO_SECRET_KEY}
DEBUG=false
ROOT_LOG_LEVEL=INFO
DJANGO_ALLOWED_HOSTS="*"
GUNICORN_BIND_PORT=8001
DOCKER_NGINX_VOLUME_ROOT=/nginx
GUNICORN_BIND_SOCKET=unix:\${DOCKER_NGINX_VOLUME_ROOT}/gunicorn.socket
NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_NAME=postgres
POSTGRES_HOST=cfg-db
POSTGRES_PORT=5432
DOCKER_WEB_VOLUME=.:/app
GUNICORN_WEB_RELOAD=false
DJANGO_SUPERUSER_PASSWORD=${ADMIN_PASSWORD}
DJANGO_SUPERUSER_USERNAME=root
DJANGO_SUPERUSER_EMAIL=admin@safe.local
DJANGO_OTP_ADMIN=false
DEFAULT_FILE_STORAGE=django.core.files.storage.FileSystemStorage
FORCE_SCRIPT_NAME=/cfg/
CGW_URL=http://nginx:8000/cgw
CGW_AUTH_TOKEN=${CGW_AUTH_TOKEN}
CSRF_TRUSTED_ORIGINS="http://${DOMAIN:-localhost}:${PORT:-8000}"
MEDIA_URL="http://${DOMAIN:-localhost}:${PORT:-8000}/cfg/media/"
EOF

cat > "${ENV_DIR}/cgw.env" <<EOF
HTTP_CLIENT_REQUEST_TIMEOUT_MILLISECONDS=60000
SAFE_CONFIG_BASE_URI=http://nginx:8000/cfg
INFURA_API_KEY='${INFURA_TOKEN:-}'
REDIS_HOST=cgw-redis
AUTH_TOKEN=${CGW_AUTH_TOKEN}
LOG_LEVEL=info
EMAIL_API_APPLICATION_CODE=''
EMAIL_API_FROM_EMAIL=noreply@safe.local
EMAIL_API_KEY=''
EMAIL_TEMPLATE_RECOVERY_TX=''
EMAIL_TEMPLATE_UNKNOWN_RECOVERY_TX=''
EMAIL_TEMPLATE_VERIFICATION_CODE=''
PUSH_NOTIFICATIONS_API_PROJECT=''
PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_CLIENT_EMAIL=''
PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_PRIVATE_KEY=''
RELAY_PROVIDER_API_KEY_OPTIMISM=''
RELAY_PROVIDER_API_KEY_BSC=''
RELAY_PROVIDER_API_KEY_GNOSIS_CHAIN=''
RELAY_PROVIDER_API_KEY_POLYGON=''
RELAY_PROVIDER_API_KEY_POLYGON_ZKEVM=''
RELAY_PROVIDER_API_KEY_BASE=''
RELAY_PROVIDER_API_KEY_ARBITRUM_ONE=''
RELAY_PROVIDER_API_KEY_AVALANCHE=''
RELAY_PROVIDER_API_KEY_LINEA=''
RELAY_PROVIDER_API_KEY_BLAST=''
RELAY_PROVIDER_API_KEY_SEPOLIA=''
STAKING_API_KEY=''
BRIDGE_API_KEY=''
STAKING_TESTNET_API_KEY=''
JWT_ISSUER=''
JWT_SECRET=''
FINGERPRINT_ENCRYPTION_KEY=''
POSTGRES_HOST=cgw-db
POSTGRES_DB=postgres
EOF

cat > "${ENV_DIR}/ui.env" <<EOF
NEXT_PUBLIC_INFURA_TOKEN=${INFURA_TOKEN:-}
NEXT_PUBLIC_GATEWAY_URL_PRODUCTION=http://${DOMAIN:-localhost}:${PORT:-8000}/cgw
NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN=${INFURA_TOKEN:-}
NEXT_PUBLIC_TENDERLY_SIMULATE_ENDPOINT_URL=${TENDERLY_SIMULATE_URL:-}
NEXT_PUBLIC_TENDERLY_PROJECT_NAME=${TENDERLY_PROJECT:-}
NEXT_PUBLIC_TENDERLY_ORG_NAME=${TENDERLY_ORG:-}
NEXT_PUBLIC_IS_PRODUCTION=true
NEXT_PUBLIC_SAFE_VERSION=1.4.1
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_BEAMER_ID=
NEXT_PUBLIC_WC_BRIDGE=
NEXT_PUBLIC_FORTMATIC_KEY=
NEXT_PUBLIC_PORTIS_KEY=
NEXT_PUBLIC_CYPRESS_MNEMONIC=
EOF

cat > "${ENV_DIR}/events.env" <<EOF
DATABASE_URL=psql://postgres:${POSTGRES_PASSWORD}@events-db:5432/postgres
AMQP_URL=amqp://general-rabbitmq:5672
AMQP_EXCHANGE=safe-transaction-service-events
AMQP_QUEUE=safe-events-service
ADMIN_EMAIL=admin@safe.local
ADMIN_PASSWORD=${ADMIN_PASSWORD}
WEBHOOKS_CACHE_TTL=300000
NODE_ENV=production
URL_BASE_PATH=/events
EOF

cat > "${ROOT_DIR}/.env" <<EOF
REVERSE_PROXY_PORT=${PORT:-8000}
CFG_VERSION=${CFG_VERSION:-latest}
CGW_VERSION=${CGW_VERSION:-latest}
TXS_VERSION=${TXS_VERSION:-latest}
UI_VERSION=${UI_VERSION:-latest}
EVENTS_VERSION=${EVENTS_VERSION:-latest}
RPC_NODE_URL=${RPC_NODE_URL}
EOF

cat > "$CREDENTIALS_FILE" <<EOF
# Safe Infrastructure Admin Credentials
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# KEEP THIS FILE SECURE!

Config Service Admin:
  URL: http://${DOMAIN:-localhost}:${PORT:-8000}/cfg/admin
  Username: root
  Password: ${ADMIN_PASSWORD}

Transaction Service Admin:
  URL: http://${DOMAIN:-localhost}:${PORT:-8000}/txs/admin
  Username: root
  Password: ${ADMIN_PASSWORD}

Events Service Admin:
  URL: http://${DOMAIN:-localhost}:${PORT:-8000}/events/admin
  Username: admin@safe.local
  Password: ${ADMIN_PASSWORD}

Database Password: ${POSTGRES_PASSWORD}
EOF

chmod 600 "$CREDENTIALS_FILE"

echo "Environment files generated successfully"
echo "Credentials saved to: $CREDENTIALS_FILE"

